version: 2.1

jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:3.3.0-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circleci-demo-workflows

  rake_test:
    parallelism: 3
    docker:
      - image: circleci/ruby:3.3.0-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: gem install bundler -v 2.1.4
      - run: bundle config set path 'vendor'
      - run: bundle install
      - run: cp config/database.yml.example config/database.yml && cp config/application.yml.example config/application.yml && cp config/secrets.yml.example config/secrets.yml
      - run: bundle exec rake db:create db:migrate
      - run: yarn install --ignore-engines
      - run:
          name: Precompile assets
          command: bundle exec rake assets:precompile
      - run:
          name: Run tests
          command: bundle exec rake

workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - rake_test:
          requires:
            - checkout_code
